name: Second Action

on:
  pull_request:
    types:
      - labeled
    branches:
      - main

jobs:
  merge-check:
    name: Merge Check
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'ready' }}
    steps:
      - uses: actions/checkout@v4
      - name: Echo Success
        run: |
          echo "SUCCESS"