name: Second Action

on:
  workflow_dispatch:
  pull_request:
    types:
      - edited
    branches:
      - main

jobs:
  merge-check:
    name: Merge Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo Success
        run: |
          echo "SUCCESS"